Repository ExpediaGroup/openworld-sdk-java-generators, pull requests merged in 2023-01, with the labels that each got.

#40 chore(build): Fix Release Issues & Upgrade Core
  openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Labels: Ready

#48 chore(downgrade): Downgrade Hibernate Validator
  openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Labels: Changes Requested

#59 feat(build): Shade Dependencies
  openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Labels: Ready

#60 fix(generation): Make `builder` Function Static
  openapi/src/main/resources/templates/openworld-sdk/api.mustache
Labels: Approved
